<?xml version="1.0"?>
<package format="3">
  <name>imu_publisher</name>
  <version>0.1.0</version>
  <description>ROS 2 driver node for publishing ICM45686 IMU data.</description>
  <maintainer email="uav@example.com">uav</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
